language: node_js
node_js:
  - "18"
  - "17"
  - "16"
  - "15"
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
os:
  - linux
  - osx
  - windows
script: npm run coverage
# Send coverage data to Coveralls
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js